# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-06-12 06:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='notes_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='notes/'),
            preserve_default=False,
        ),
    ]
